name: Onedrive File Triggered Workflow

on:
  repository_dispatch:
    types: [onedriveFileCreated]  # match the event_type we'll send from Power Automate

jobs:
  processOnedriveFile:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Print debug info
        run: |
          echo "Triggered by OneDrive file creation!"
          # GitHub surfaces the payload at github.event.client_payload
          echo "File Name: ${{ github.event.client_payload.fileName }}"
          echo "File Path: ${{ github.event.client_payload.filePath }}"

      - name: Run my script
        run: python scripts/transform_data.py
